# Файл конфигурации линтера
# Подробнее о ней можно посмотреть в https://github.com/DavidAnson/markdownlint#configuration
# Пример можно посмотреть в https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml
# Данная конфигурация распространяется ГЛОБАЛЬНО на все .md файлы, перед тем как запрашивать в ней изменения, сначала убедитесь, что они принесут пользу, а не вред!


# Чёрный список правил (глобальные отключения)
# Если нужно отключить правило только в определённой статье, используйте комментарий <!-- markdownlint-disable ПРАВИЛА -->
# Пример: <!-- markdownlint-disable MD22919 MD234211 и т.д -->


# line-length (проверка на длину строки)
# https://github.com/DavidAnson/markdownlint/blob/main/doc/md013.md
# Отсутствует смысл правила (гитхаб и вайтпресс могут отрисовывать текст любой длины)
MD013: false

# no-inline-html (HTML тэги в Markdown)
# https://github.com/DavidAnson/markdownlint/blob/main/doc/md033.md
# Бывает, нужно встраивать Vue-компоненты, как в MDX
MD033: false

# no-bare-urls (угловые скобки в ссылках и электронных почтах, или же <https://example.com> вместо https://example.com)
# https://github.com/DavidAnson/markdownlint/blob/main/doc/md034.md
# Отсутствует смысл правила + мешает в работе (гитхаб и вайтпресс могут отрисовывать ссылки и без угловых скобок, а вставлять их всё время на постоянной основе - такая себе работа)
MD034: false

# no-alt-text (Обязательное наличие альтернативного текста, или же ![Альтернативный текст](image.png) вместо ![](image.png))
# https://github.com/DavidAnson/markdownlint/blob/main/doc/md045.md
# Альтернативный текст предназначен для тех людей, которые не видят саму фотографию (слепые/люди с отключенным отображением фотографий в браузере) и гораздо больше предпочтут её описание. В принуждении его указывания имеются две неразрешимые проблемы:
# 1. Таким людям в вики делать нечего (вайтпресс под них не подстроен и его невозможно подстроить);
# 2. В большинстве случаев к фотографии либо невозможно придумать альтернативный текст, либо же он не всегда является информативным: авторы придумывают в нём либо белиберду, либо не самое информативное описание (по типу "Создание чего-либо", "Процесс установки", "Image 1" и т.п) по указанию линтера/по незнанию того, что его можно не указывать, оставив квадратные скобки пустыми.
MD045: false

# ol-prefix (Корректная нумерация в нумерованных списках)
# https://github.com/DavidAnson/markdownlint/blob/main/doc/md029.md
# Не решает проблему с нумерацией полностью: чаще всего линтер ругается из-за блоков кода/подсказок, а не из-за некорректной нумерации
MD029: false


# Частичные ограничения (изменения некоторых параметров в определённых правилах)


# no-trailing-punctuation (пунктуация в заголовках)
# https://github.com/DavidAnson/markdownlint/blob/main/doc/md026.md                                 
# Пунктуация действительно не нужна в заголовках, но не абсолютно вся (в частности, двоеточие не должно попадать под запрет линтером)
# ref: https://wiki.play2go.cloud/host/pythonlibs
MD026:
  # Снизу - запрещённая пунктуация
  punctuation: ".,;!。，；！"
