# Глобальные отключения правил
# Если нужно отключить правило только в определённой статье, используйте комментарий <!-- markdownlint-disable ПРАВИЛА -->
# Пример: <!-- markdownlint-disable MD22919 MD234211 и т.д -->
# Подробнее о конфигурации можно посмотреть в https://github.com/DavidAnson/markdownlint#configuration

# Отключает проверку на длину строки
MD013: false

# Отключает проверку на HTML в MD
# Бывает нужно встраивать Vue-компоненты, как в MDX
MD033: false

# Отключает проверку пунктуации в заголовках
MD026: false
