# Отключает проверку на длину строки
MD013: false

# Отключает проверку на HTML в MD
# Бывает нужно встраивать Vue-компоненты, как в MDX
MD033: false

# Отключает проверку пунктуации в заголовках
MD026: false
